version: '3'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "3000"
    networks:
      - theses-network
    volumes:
      - .:/theses
    links:
      - mongo
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "4000"
    networks:
      - theses-network
    volumes:
      - .:/theses
  admin:
    container_name: admin
    restart: always
    build:
      context: .
      dockerfile: admin.dockerfile
    ports:
      - "5000"
    networks:
      - theses-network
    volumes:
      - .:/theses
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - "27017"
    networks:
      - theses-network
    volumes:
      - mongodbdata:/data/db
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - theses-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
volumes:
  mongodbdata:
    external: true
networks:
  theses-network:
    external: true
